language: java
sudo: false

jdk:
  - oraclejdk8

script:
  - ./travis.sh

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar

notifications:
  email: false
  webhooks:
    - secure: "e6/3Wlr9+ArBpoy+FCwXJ3hJEnHQBe5bnfWyg60SNwqDjJj2TsSQvz2dpp/PCU4sRnf0bzlML+WZ5u7ZsW+qRFMSVu+s5flhdHCNm6cIPwTvikqdXDGquP7GMMsyYlfDyAmgpkeowg3Z2fbgAtOG1ENQIH6eM294skQvAb73yp4="
  on_start: always

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "jose-tissei"
  - git config --local user.email "jose.tissei@benner.com.br"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
      secure: GITHUB_API_KEY_ENCRYPTED
  file: $HOME/build/jose-tissei/sonar-github/target/sonar-github-plugin-1.2-sources.jar
  skip_cleanup: true
  on:
    tags: true  

    

addons:
  apt:
    packages:
      # upgrade java 8 as the default version 1.8.0_31 prevents from compiling sources
      # https://github.com/travis-ci/travis-ci/issues/4042
      - oracle-java8-installer
